version: '3.8'

services:
  tic-tac-toe:
    build: .
    container_name: tic-tac-toe-game
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - game-network

networks:
  game-network:
    driver: bridge

# Optional: Add volume for logs
volumes:
  nginx_logs:
    driver: local